#%RAML 1.0 DataType
#This file is located at dataTypes/EmployeeResponse.raml

type: object
properties: 
  id: string 
  employeeSfdcUrl: string
  employeeNetsuiteUrl: string
  employeeWorkdayUrl: string